const PRAWDA = document.getElementById('prawda')
const WYZWANIE = document.getElementById('wyzwanie')
const TEKST  = document.getElementById('tresc')
const RESET = document.querySelector('.reset')

let iloscPrawd = parseInt(0)
let iloscWyzwan = parseInt(0)

let pyt = [
    'Jaki był najbardziej nieoczekiwany incydent w twoim życiu?',
    'Które z miejsc chciałbyś/aś odwiedzić najbardziej?',
    'W tej sali, komu wierzysz najmniej, a komu najbardziej?',
    'Jak nazywała się twoja pierwsza miłość?',
    'Do kogo byś wezwał/a pomoc w pochowaniu martwego ciała?',
    'Czy kiedykolwiek zdradziłeś/aś swojego partner?',
    'Kiedy ostatnio kogoś okłamałeś i dlaczego?',
    'Jaka jest najgorsza rzecz, jaką kiedykolwiek powiedziałeś o kimś innym?',
    'Co lubisz robić z przyjaciółmi, czego nigdy byś nie robił/a przy swoim partnerze?',
    'O kogo jesteś najbardziej zazdrosny?',
    'Czego najbardziej bałeś/aś się w dzieciństwie?',
    'Czy kiedykolwiek przypadkowo uderzyłeś w coś swoim pojazdem?',
    'Czy umówiłabyś/aś się dzisiaj ze swoją pierwszą miłością?',
    'Gdzie masz łaskotki?',
    'Czy wierzysz w kosmitów?',
    'Jaki jest twój najbardziej wstydliwy nawyk?',
    'Jaka jest ostatnia wiadomość, którą wysłałeś do swojego najlepszego przyjaciela?',
    'Jaki był ostatni raz, kiedy zwymiotowałeś/aś z powodu nadmiernego picia?',
    'Gdybyś miał gwarancję, że nigdy nie zostaniesz złapany, kogo byś zamordował/a?',
    'Jaką tajemnicę miałeś jako dziecko, o której nigdy nie powiedziałeś rodzicom?',
    'Czy kiedykolwiek miałeś profil w aplikacji randkowej?',
    'Jaka jest najdziwniejsza rzecz, jaką zrobiłeś na imprezie?',
    'Czy kiedykolwiek zostałeś ukarany, ponieważ zrobiłeś/aś coś nieodpowiedniego?',
    'Jakie jest najgorsze jedzenie, jakie kiedykolwiek jadłeś?',
    'Czy kiedykolwiek zepsułeś/aś drogi przedmiot w sklepie, a potem wyszedłeś?',
    'Czy kiedykolwiek skłamałeś na temat swojego wieku? I dlaczego?',
    'Gdybyś musiał/a usunąć jedną aplikację z telefonu, która by to była?',
    'Gdybyś musiał/a zostawić jedną aplikację z telefonu do końca życia, która by to była?',
    'Czy kiedykolwiek używałeś fałszywego dokumentu tożsamości?',
    'Czy kiedykolwiek paliłeś marihuanę?',
    'Masz ulubione dziecko, przyjaciela lub rodzica? Wymień je.',
    'Gdybyś obudził/a się pewnego dnia jako druga płeć, co byś zrobił najpierw?',
    'Co jest twoim największym strachem w związku?',
    'Czy kiedykolwiek podsłuchiwałeś telefon swojej drugiej połówki?',
    'Jaki jest najbardziej wstydliwy tekst, który otrzymałeś ostatnio w wiadomościach czatu?',
    'Czy masz zwyczaj śpiewać pod prysznicem?',
    'Czy kiedykolwiek ukradłeś/aś coś z domu twojej drugiej połówki/przyjaciela?',
    'Jaki był najdłuższy czas bez umycia zębów?',
    'Czy kiedykolwiek rozmawiałeś ze sobą w lustrze?',
    'Opisz najdziwniejszą rzecz, jaką kiedykolwiek zrobiłeś będąc nietrzeźwym.',
    'Zostawiłbyś swojego partnera za milion dolarów?',
    'Czy kiedykolwiek zakochałeś się w swoim najlepszym przyjacielu/przyjaciółce?',
    'Czy kiedykolwiek żałowałeś czegoś, co zrobiłeś, żeby się zakochać lub zwrócić na siebie uwagę partnera?',
    'Czy kiedykolwiek puszciłeś głośno bąka w miejscu publicznym?',
    'Czy kiedykolwiek zdarzyło Ci się naśladować przyjaciela/drugą połówkę?',
    'Co ci się we mnie nie podoba?',
    'Jakie jest najbardziej skandaliczne zdjęcie w Twojej chmurze?',
    'Kogo najmniej lubisz w tym pokoju i dlaczego?',
    'Jaki masz najgorszy nawyk?',
    'Kiedy ostatni raz pisałeś/aś do swojego byłego?',
    'Gdybyś musiała/ł wybrać inne miejsce do życia, które to miejsce?',
    'Umówiłbyś się z kimś niższym od ciebie?',
    'Czy kiedykolwiek łowiłeś ryby?',
    'Wymień jedną rzecz, którą byś zmieniła w swoim partnerze.',
    'Kiedy ostatni raz sprawiłaś/eś, że ktoś inny płakał?',
    'Czy śpisz z wypchanym zwierzęciem?',
    'Jeśli możesz mieć dzień, w którym możesz robić, co chcesz, powiedz nam pierwsze trzy rzeczy, które zrobisz.',
    'Czy kiedykolwiek zdenerwowałeś się na przyjaciela za opublikowanie niepochlebnego zdjęcia?',
    'Czy kiedykolwiek jadłeś coś, co znalazłeś na ziemi?',
    'Czy masz koc bezpieczeństwa?',
    'Czy kiedykolwiek pocałowałeś kogoś swojej płci?',
    'Jaka byłaby najdziwniejsza rzecz, którą znalazłbyś w swojej szafce, gdybym przez nią przejrzał?',
    'Jakie jest najgorsze danie restauracyjne, jakie kiedykolwiek jadłeś?',
    'Jaka jest Twoja najpotężniejsza atrakcja?',
    'Czy kiedykolwiek zdarzyło Ci się otrzymać straszny pocałunek?',
    'Czego boisz się najbardziej w codziennym życiu?',
    'Czy kiedykolwiek jeździłeś bez prawa jazdy?',
    'Czy byłeś kiedyś na imprezie nieproszony?',
    'Czy kiedykolwiek zniszczyłeś przyjęcie niespodziankę?',
    'Czy kiedykolwiek oszukiwałeś na teście? W jaki sposób?',
    'Czy kiedykolwiek spotykałeś się z kimś, kogo naprawdę nienawidzisz? ',
    'Które danie najbardziej lubisz, śniadanie, obiad czy kolację?',
    'Wolisz włączać czy wyłączać światło?',
    'Czy kiedykolwiek całowałeś się w śmierdzącej łazience?',
    'Jakie było twoje pierwsze randkowanie?',
    'Czy kiedykolwiek byłeś/aś tak głośno, że ktoś na to narzekał?',
    'Kiedy ostatnio nie czułeś się sobą?',
    'Jaka jest najdziwniejsza rzecz, jaką ty i twój partner zrobiliście razem?',
    'Czy zdarzyło Ci się kiedyś mieć sytuację późną nocą, która, jak sądzisz, nigdy nie przydarzy się nikomu innemu?',
    'Jaka była twoja najbardziej przerażająca randka i dlaczego?',
    'Jak myślisz, jaki rodzaj stroju najbardziej Ci odpowiada?',
    'Czy kiedykolwiek całowałeś się z kimś tej samej płci?',
    'Jeśli nagle spotkasz swojego byłego, jak myślisz, jak byś zareagował?',
    'Czy Twój partner kiedykolwiek Cię zdradził? A ty go?',
    'Czy kiedykolwiek myślałeś o zdradzie swojego partnera?',
    'Czego najbardziej nienawidzisz w swoim partnerze?',
    'Czy robisz coś dziwnego, kiedy idziesz na randkę?',
    'Czy kiedykolwiek udawałeś, że kogoś kochasz?',
    'Kiedy ostatnio zostałeś porzucony?',
    'Czy kiedykolwiek myślałeś o zerwaniu ze swoim partnerem, ale tego nie zrobiłeś?',
    'Czy kiedykolwiek spotykałeś się z dwiema osobami jednocześnie, aby podjąć ostateczną decyzję?',
    'Jaka jest ostatnia rzecz, której szukałeś w telefonie?',
    'Kiedy ostatnio puściłeś bąka w miejscu publicznym?',
    'Jeśli miałbyś mieć trójkąt z ludźmi w tym pokoju, kogo byś wybrała?',
    'Czy są jakieś przygody, które chciałbyś odbyć?',
    'Czy jest jakieś dziwne miejsce, które sam odkryłeś?',
    'Jak myślisz, kto był twoim najlepszym partnerem do tej pory?',
    'W jakim wieku miałeś swój pierwszy pocałunek?',
    'Jak myślisz, jaka jest najbardziej ryzykowna rzecz, jaką zrobiłeś do tej pory?',
    'Której części ciała nienawidzisz najbardziej?',
    'Czy kiedykolwiek oszukałeś kogoś podczas grania w prawdę czy wyzwanie?',
    'Czy masz zauroczenie celebrytą?',
    'Czy kiedykolwiek miałeś sen o znanej osobie?',
    'Udostępnij nam ostatnią wiadomość głosową, którą wysłałeś do swojego byłego.',
    'Co najbardziej lubisz w osobie naprzeciwko?',
    'Kiedy ostatnio myślałeś o kimś z tego pokoju pod prysznicem?',
    'Co najbardziej lubisz, całowanie czy przytulanie?',
    'Czy wybrałbyś/a miłość zamiast kariery?',
    'Jaka jest jedna rzecz, którą chciałbyś zrobić przed śmiercią?',
    'Jaka jest najlepsza rada, jaką ktoś ci kiedykolwiek dał?',
    'Gdybyś mógł mieszkać w dowolnym miejscu na świecie, jakie miejsce byś wybrał?',
    'Jakie jest Twoje ulubione wspomnienie z dzieciństwa?',
    'Jaka była najbardziej ryzykowna rzecz, jaką kiedykolwiek zrobiłeś?',
    'Gdybyś mógł mieć jakąś supermoc, jaka by to była i dlaczego?',
    'Jaka jest Twoja największa obawa i jak sobie z tym radzisz?',
    'Gdybyś mógł na jeden dzień zamienić się z kimś życiem, kto by to był? Z tego pokoju.',
    'Jaka jest najtrudniejsza rzecz, jakiej kiedykolwiek dokonałeś?',
    'Czy miałeś kiedyś sen, który wydawał Ci się realny? Udostępnij go!',
    'Czego zawsze chciałeś się nauczyć lub spróbować, ale jeszcze tego nie zrobiłeś?',
    'Jaki jest najbardziej zapadający w pamięć prezent, jaki kiedykolwiek otrzymałeś?',
    'Jaka jest najbardziej zawstydzająca rzecz, którą zrobiłeś przed zakochaną osobą?',
    'Jaki jest Twój ulubiony sposób na relaks i odpoczynek?',
    'Gdybyś mógł być świadkiem dowolnego wydarzenia historycznego, które byś wybrał?',
    'Jaki jest najbardziej pamiętny sen, jaki kiedykolwiek miałeś?',
    'Jaka jest najcenniejsza lekcja, jaką wyciągnąłeś z porażki?',
    'O co zawsze chciałeś zapytać swoich rodziców, ale jeszcze tego nie zrobiłeś?',
    'Gdybyś mógł porozmawiać ze swoim przyszłym ja, o co byś zapytał?',
    'Jaka jest Twoja najcenniejsza rzecz i dlaczego?',
    'Gdybyś mógł zmienić jedną rzecz na świecie, co by to było?',
    'Jaka jest najbardziej spontaniczna rzecz, jaką kiedykolwiek zrobiłeś?',
    'Gdybyś mógł cofnąć się w czasie, jaką epokę byś odwiedził?',
    'Jaka jest Twoja ulubiona książka lub film i dlaczego?',
    'Gdybyś mógł mieć jakieś zwierzę jako zwierzątko domowe, jakie by to było?',
    'Jaki jest Twój ulubiony sposób wyrażania swojej kreatywności?',
    'Jaka jest Twoja najcenniejsza przyjaźń i dlaczego jest wyjątkowa?',
    'Jaki jest Twój pomysł na idealną randkę?',
    'Czego szukasz u partnera?',
    'Co najbardziej w sobie lubisz?',
    'Co najbardziej lubisz w osobie na przeciwko?',
    'Czy kiedykolwiek byłeś w kimś zakochany przez ponad rok?',
    'Jakie jest Twoje wymarzone miejsce na wakacje?',
    'Jaki jest Twój ulubiony sposób spędzania z kimś czasu?',
    'Jaki jest najbardziej przemyślany prezent, jaki kiedykolwiek dałeś lub otrzymałeś?',
    'Jaki jest najsłodszy komplement, jaki kiedykolwiek usłyszałeś?',
    'Jaka jest dla Ciebie najważniejsza cecha partnera?',
    'Czy kiedykolwiek zakochałeś się w fikcyjnej postaci?',
    'Jaka jest najbardziej pamiętna randka, na której kiedykolwiek byłeś?',
    'Jaka jest najtrudniejsza rzecz, przez którą kiedykolwiek przeszedłeś?',
    'Czego nauczyłeś się w dzieciństwie i czego przestrzegasz do dziś?',
    'Co podziwiasz w każdym członku rodziny?',
    'Jaka jest najbardziej zawstydzająca rzecz, jaką twoi rodzice kiedykolwiek zrobili publicznie?',
    'Jaki jest twój największy lęk?',
    'Kiedy ostatnio płakałeś/aś?',
    'Która osoba w Twoim życiu miała na Ciebie największy wpływ?',
    'Jaka była Twoja największa wpadka?',
    'Najdziwniejsza rzecz jaką kiedykolwiek zrobiłeś przed lustrem',
    'Co cię najbardziej przeraża w dorosłym życiu?',
    'Czy kiedykolwiek złamałeś prawo?',
    'Gdybyś mógł zamienić się życiem z kimkolwiek w tym pokoju, kto by to był?',
    'Kogo zabrałbyś na bezludną wyspę',
    'Jaka jest najgorsza rzecz, jaką zrobiłeś w szkole?',
    'Jaki jest Twój ulubiony przedmiot w szkole i dlaczego?',
    'Jaki jest Twój największy skarb?',
    'Jaka jest Twoja ulubiona gra planszowa lub karciana?',
    'Co uważasz za swoją największą wartość?',
    'Jaki jest Twój ulubiony sport?',
    'Co uważasz za swoją największą słabość?',
    'Co jest dla ciebie głównym powodem, dla którego jesteś ze swoim partnerem?',
    'Czy masz dziwny nawyk?',
    'Ile dzieci chcesz mieć?',
    'Czy masz pseudonim z dzieciństwa?',
    'Czy kiedykolwiek rozważałbyś bycie nudystą?',
    'Jaka jest Twoja wymarzona praca?',
    'W jakim kraju chciałbyś mieszkać, jeśli chcesz wybrać?',
    'Jaka jest twoja grzeszna przyjemność?',
    'Czy wierzysz w miłość od pierwszego wejrzenia?',
    'Czy w Twojej przeszłości jest coś, z czym chciałbyś się wyjawić?',
    'Gdybyś mógł zmienić coś w swoim ciele, co by to było?',
    'Jaki jest twój największy talent?',
    'Jaki jest twój ulubiony kolor?',
    'Jaki jest rozmiar twojego buta?',
    'Czy kiedykolwiek okradłeś swoją mamę lub tatę?',
    'Jaka jest najbardziej irytująca rzecz, którą robi mama',
    'Jaka jest najbardziej irytująca rzecz, jaką robi tata?',
    'Ile razy wymykałeś się z domu?',
    'Jakie jest najlepsze i najgorsze danie, które robi mama?',
    'Gdybyś mógł pozbyć się jednego obowiązku domowego, co by to było?',
    'Czy możesz wymienić swojego najlepiej wyglądającego nauczyciela, jakiego kiedykolwiek miałeś?',
    'Czy możesz wymienić dla siebie najbardziej denerwującą osobę?',
    'Czy kiedykolwiek zrobiłeś kawał swojemu nauczycielowi?',
    'Czy kiedykolwiek okłamałeś swoich rodziców, co robisz po szkole?',
    'Czy kiedykolwiek obwiniałeś swoje rodzeństwo za coś, co zrobiłeś?',
    'Czy kierujesz się w życiu jakąś zasadą?',
    'Czy popierasz pogląd, że romans w miejscu pracy nie powinien być dozwolony?',
    'Gdybyś miał szansę pracować w dowolnym miejscu, dokąd byś się udał?',
    'Jaka jest Twoja ulubiona rasa psa?',
    'Jaka jest jedna rzecz, którą zawsze nosisz ze sobą, gdziekolwiek jesteś?',
    'Miasto czy wieś?',
    'Wolisz mieć więcej czasu czy więcej pieniędzy?',
    'Czy wolałbyś nowy dom czy nowy samochód?',
    'Jak widzisz siebie za pięć lat?',
    'Dlaczego uważasz ____ jako swojego najlepszego przyjaciela?',
    'Jaka jest najsłodsza rzecz, jaką zrobiłeś dla przyjaciela?',
    'Kto był ostatnią osobą, którą obserwowałeś na Instagramie i dlaczego ją obserwowałeś?',
    'Jakie rodzaje filmów oglądasz w YouTube?',
    'Kto jest Twoim ulubionym influencerem w mediach społecznościowych i dlaczego?',
    'Co sądzisz o tragicznych wydarzeniach 2020 roku?',
    'Twoim zdaniem, co może wyeliminować ubóstwo?',
    'Jaka jest najlepsza inwestycja, jaką możesz teraz zrobić?',
    'Czy wierzysz we wszystko, co rząd mówi wszystkim?',
    'Gdybyś miał szansę, skończyłbyś swoje życie? Dlaczego lub dlaczego nie?',
    'Opowiedz mi o swoich przemyśleniach na temat równości płci i społeczności LGBTQ.',
    'Kto jest twoim wzorem do naśladowania i dlaczego?',
    'Kim chcesz być, gdy dorośniesz?',
    'Czy myślisz, że przeżyłbyś samodzielnie w innym kraju?',
    'Gdybyś miał dziś umrzeć, czego nie będziesz żałować?',
    'Jaki jest Twój pomysł na zdrowy związek?',
    'Czy kiedykolwiek próbowałeś diety?',
    'Jakie są wady i zalety mediów społecznościowych?',
    'A jeśli jutro umrzesz?',
    'Opowiedz mi o swoim dzieciństwie.',
    'Jak myślisz, jaka jest najgorsza rzecz, jaka może się wydarzyć?',
    'Kim są twoi najlepsi przyjaciele?',
    'Gdybyś miał lwa, jak byś go nazwał i dlaczego?',
    'Co sprawia, że jesteś naprawdę szczęśliwy?',
    'Jakie są twoje ulubione gry do grania ze znajomymi?',
    'Opowiedz nam o swoim najmniej ulubionym przedmiocie w szkole.',
    'Czy myślisz, że zwierzęta nas rozumieją?',
    'Jak spędzasz weekendy?',
    'Jak myślisz, jaki sok jest najpyszniejszy ze wszystkich?',
    'Jakie jest najlepsze dzieło sztuki, które zrobiłeś i jak to zrobiłeś?',
    'Czy możesz pomyśleć o najdziwniejszym śnie, jaki miałeś i podzielić się nim z nami?',
    'Jak możesz stać się lepszą wersją siebie?',
    'Za jakie trzy rzeczy jesteś najbardziej wdzięczny?',
    'Gdybyś kiedyś był sławny, jak myślisz, z czego byłbyś sławny?',
    'Co zwykle robisz, gdy nie możesz spać w nocy?',
    'Czy myślisz, że pewnego dnia odniesiesz sukces?',
    'Gdybyś miał zmieniacz czasu, taki jak Hermiona w Harrym Potterze i Więzieniu Azkabanu, co byś zmienił?',
    'Jakie są najlepsze miejsca, w których kiedykolwiek byłeś?',
    'Opowiedz mi o swoim ulubionym vlogerze na YouTube.',
    'Czy myślisz, że możesz dokładnie określić ostatni dzień, w którym będziesz uważany za dziecko?',
    'Jak radzisz sobie ze złamanym sercem?',
    'To ostatni dzień akacji, jak go spędzisz?',
    'Opisz swój najgorszy dzień w życiu.',
    'Kim są trzy osoby, którym powierzyłbyś swoje życie?',
    'Czy pieniądze naprawdę dają szczęście?',
    'Jakie rzeczy chciałbyś w sobie poprawić?',
    'Opisz idealny dzień dla siebie.',
    'Powiedz mi trzy dobre dowcipy, które znasz.',
    'Jakie są najważniejsze rzeczy w życiu?',
    'Jak radzisz sobie ze wszystkimi swoimi lękami?',
    'Jaka jest dla ciebie najbardziej irytująca maniera?',
    'Czy uważasz, że życie w teraźniejszości jest o wiele trudniejsze niż życie w przeszłości?',
    'Jak myślisz, ile musisz oszczędzać, aż wystarczy, abyś na zawsze przestał pracować?',
    'Jakie są cechy wspaniałej gospodyni?',
    'Jakie problemy społeczne Cię najbardziej niepokoją?',
    'Opisz osobę, którą chcesz być.',
    'Czego nienawidzisz w byciu chlopakiem / dziewczyną / kobietą?',
    'Jak zazwyczaj zwracasz się do ludzi, których nie lubisz?',
    'Czy masz dziwną rodzinną tradycję?',
    'Jak myślisz, kto jest najbardziej szaloną osobą, jaką znasz?',
    'Kim są twoi ulubieni aktorzy i aktorki?',
    'Powiedz nam, co może sprawić, że przestaniesz płakać.',
    'Opowiedz mi więcej o hobby, które zazwyczaj nie jest uprawiane przez większość kobiet.',
    'Jakie czynności sprawiły Ci wiele satysfakcji?',
    'Czy możesz nam opowiedzieć o jednym prostym błędzie, który popełniłeś, który miał dramatyczne konsekwencje?',
    'Jakie rzeczy chciałbyś wiedzieć, gdy byłeś młodszy?',
    'Opowiedz nam o ekscytującym sposobie poznawania nowych ludzi.',
    'Jak myślisz, jaka jest najgorsza cecha, jaką może mieć dana osoba?',
    'Myślisz, że jest w tobie coś dziwnego?',
    'Kto był ostatnią osobą, która złamała ci serce?',
    'Jakie obowiązki potajemnie lubisz robić?',
    'Czy masz rodzinną tradycję, którą obiecujesz kontynuowac?',
    'Czy jesteś w czymś ekspertem?',
    'Jaki jest twój ulubiony zapach?',
    'Czy czujesz się komfortowo, jedząc samotnie poza domem?',
    'Masz kolekcję, o której nikt nie wie?',
    'Czy chcesz mieć tatuaż?',
    'Czy jesteś w stanie swobodnie wyrażać swoje opinie?',
    'Masz samochód marzeń?',
    'W jakie teorie spiskowe wierzysz?',
    'Jaka jest najdziwniejsza rzecz, którą oglądałeś online?',
    'Jakie witryny odwiedzasz codziennie?',
    'Jaka jest najgłupsza rzecz, na jaką kiedykolwiek zgodziłeś się zrobić jako wyzwanie?',
    'Czy możesz przetrwać bez mediów społecznościowych? Jeśli możesz zachować tylko jedną, którą platformę byś wybrał?',
    'Czy wierzysz w zjawiska paranormalne?',
    'Jeśli dżin spełni trzy życzenia, jakie by one były?',
    'Kawa czy herbata?',
    'Netflix czy iść do kina?',
    'Przeczytać książkę czy posłuchać muzyki?',
    'Pominąć śniadanie czy kolację?',
    'Śmierć przez rekina czy zombie?',
    'Czy masz dziwny powtarzający się sen?',
    'Gdybyś mógł płynnie nauczyć się języka, jaki byś wybrał?',
    'Którego dnia nigdy nie zapomnisz?',
    'Jeśli możesz zdobyć dinozaura lub smoka jako zwierzaka, który byś wybrał?',
    'Czy ktoś z tego pokoju zrobił ci coś, czego nigdy nie zapomnisz?',
    'Jaka jest ostatnia rzecz, którą zrobiłeś po raz pierwszy?',
    'Jakie było najbardziej imponujące wydarzenie, w którym uczestniczyłeś?',
    'Jaki jest twój najbardziej dumny moment w życiu?',
    'Czy są jakieś szczególne momenty w twoim dzieciństwie, które ukształtowały to, kim jesteś dzisiaj?',
    'Co najbardziej cenisz w przyjaźniach?',
    'Czy masz przeczucie, jaka byłaby twoja przyczyna śmierci?',
    'Czy masz słabość, którą próbujesz przezwyciężyć?',
    'Wolałbyś pochówek czy kremację?',
    'Za jakie 3 rzeczy jesteś dziś najbardziej wdzięczny?',
    'Czy jesteś teraz zadowolony ze swojego życia?',
    'Jakiego szalonego wyzwania chcesz kiedyś spróbować?',
    'Co zrobisz jutro od razu po przebudzeniu?',
    'Jaką najdziwniejszą rzecz zjadłeś/zjadłaś w życiu?',
    'Czy wygrałeś kiedyś big milka?',
    'Czy dzwoniłeś kiedyś na 112?',
    'W jaki sposób odkryłeś, że św. Mikołaj nie istnieje?',
    'Czy uważasz się za osobę nieśmiałą?',
    'Z kim jest twój wymarzony pocałunek?',
    'Czy cieszysz się ze swojej płci?',
    'Czy podobał ci się ktoś tej samej płci co ty?',
    'Najbardziej szalona rzecz, której szukałeś w Internecie?',
    'Czy czułeś pociąg do członka rodziny?',
    'Czy kiedykolwiek kogoś oszukałeś?',
    'Jakie było najgorsze kłamstwo, które powiedziałeś?',
    'Czy zabiłbyś kogoś w zamian za milion euro?',
    'Kto Twoim zdaniem jest najatrakcyjniejszy z obecnych tutaj?',
    'Jaka jest najbardziej dziecinna rzecz, którą nadal robisz?',
    'Czego najbardziej nienawidzisz w obecnych tutaj?',
    'Jakie jest twoje zdjęcie, którego najbardziej się wstydzisz?',
    'Co byś zrobił, gdybyś znalazł na ulicy teczkę pełną pieniędzy?',
    'Najgorsza rzecz, jaką mogą o tobie powiedzieć inni? A najlepsze?',
    'Czy kiedykolwiek sikałeś ze śmiechu?',
    'Kiedy ostatnio zwymiotowałeś?',
    'Kogo nie możesz znieść?',
    'Co pomyślałeś o mnie, gdy zobaczyłeś każdego gracza po raz pierwszy?',
    'Nadal sypiasz z pluszakiem?',
    'Jakie myśli nie pozwalają ci spać w nocy?',
    'Komu najbardziej ufasz?',
    'Komu ufasz najmniej?',
    'Jak opisałabyś swoje relacje z rodzicami?',
    'Czy w dzieciństwie miałeś wyimaginowanego przyjaciela?',
    'Boisz się zestarzeć?',
    'Czy kiedykolwiek dałeś komuś drugą szansę?',
    'Gdybyś mógł zamienić się życiem z kimkolwiek w tym pokoju, kto by to był?',
    'Co cię najbardziej przeraża w dorosłym życiu?',
    'Jak opisałbyś swoje poczucie stylu w skali 1-10?',
    'Czy rozniosłeś(-łaś) kiedyś plotkę na czyjś temat?',
    'Jakie są trzy rzeczy, których nikt o Tobie nie wie?',
    'Jesteś rasistą?',
    'Jakie jest Twoje ulubione ciasto?',
    'Pytanie wymyśla reszta grupy',
    'Oceń każdego gracza w skali od 1 do 10.',
    'Jak długo wierzyłeś, że dzieci przynosi bocian?',
    'Kto z grupy najgorzej opowiada dowcipy?',
    'Która z obecnych tu osób jest najgorzej ubrana?',
    'Jaka jest Twoja ulubiona gra?',
    'Czy spałeś/aś kiedyś pod namiotem?',
    'Kto jest najśmieszniejszy z wszystkich graczy?',
    'Jakie lubisz kwiaty?',
    'O czym teraz myślisz?',
    'Co najbardziej złośliwego zrobiłeś do tej pory?',
    'Jaki jest Twój ulubiony napój?',
    'Jakiego pytania nie chcesz najbardziej usłyszeć w tej grze?',
    'Czy masz wścibskich sąsiadów?',
    'Czy lubisz horrory?',
    'Gdyby twój dom się palił, które 3 rzeczy być zabrał/a ze sobą?',
    'Jaka jedna wada wystarczy, abyś z kimś zerwał?',
    'Jaka jest Twoja ulubiona gra planszowa?',
    'W ilu procentach liczy się dla Ciebie wygląd?',
    'Jaki jest twój ulubiony rodzaj orzechów?',
    'Jesteś osobą tolerancyjną?',
    'Jakie masz postanowienia noworoczne',
    'Czy dłubałeś/aś sobie palcem w tyłku?',
    'Kto ma najładniejszy uśmiech?',
    'Czy zasnąłeś kiedyś na zajęciach?',
    'Jaki jest Twój ulubiony sklep?',
    'Czy lubisz kąpiele w pianie?',

]
let wyz = [
    'Zrób hałas dzikich zwierząt.',
    'Zjedz papryczkę chili ',
    'Wyświetl w telefonie najbardziej upokarzającą cię wiadomość tekstową.',
    'Tańcząc do ulubionej piosenki, zrób serię zdjęć.',
    'Staraj się nie używać rąk do wypicia szklanki wody.',
    'Pozwól innym graczom stworzyć zabawną kombinację posiłków i trochę poeksperymentować.',
    'Włóż jedną kostkę lodu do kieszeni spodni.',
    'Daj buziaka komu chcesz.',
    'Poproś sąsiada o cukier, pukając do jego drzwi.',
    'Wyj jak wilk',
    'Czołgaj się po podłodze jak dziecko',
    'Niech ktoś ogoli ci lewą nogę.',
    'Spróbuj włożyć jajko do ust na kilka minut, nie rozbijając go',
    'Udawaj, że jesteś osobą, która siedzi tuż obok ciebie',
    'Pozwól osobie po twojej lewej stronie wykonać rysunek długopisem na twojej twarzy.',
    'Przygotuj posiłek z zawiązanymi oczami i zaserwuj go swojemu towarzyszowi.',
    'Opowiedz nam o swoim najgorszym doświadczeniu w związku.',
    'Podziel się najbardziej żenującym zdjęciem z albumu na mediach społecznościowych.',
    'Podziel się z nami swoją najgłębszą tajemnicą.',
    'Przez trzy minuty masuj stopy partnera.',
    'Nałóż kosmetyki na twarz swojej sympatii.',
    'Tańcz do ulubionej muzyki z kimś w pokoju.',
    'Wykonaj wszystkie czynności związane z ulubioną rymowanką.',
    'Pozwól swojemu kochankowi użyć twojego konta w mediach społecznościowych, aby coś opublikować.',
    'Przez następne dwie minuty zawiążemy ci oczy i będziemy cię łaskotać.',
    'Patrz mi w oczy przez minutę bez mrugnięcia okiem',
    'Zadzwoń do swojej ulubionej osoby i wyraź swoją miłość do niej.',
    'Nie robiąc mimiki, opowiedz nam o swoim najmilszym wspomnieniu związanym z twoim związkiem.',
    'Zadzwoń do swojego wykładowcy i wyraź swoje prawdziwe uczucia dotyczące uczelni.',
    'Użyj ust, aby wydać dźwięk pierdnięcia i nagraj go',
    'Łaskocz swojego kochanka przez dwie minuty z zawiązanymi oczami.',
    'Nawiąż połączenie wideo ze swoją sympatią i wpatruj się w nią przez dwie minuty.',
    'Zadzwoń do swojego byłego i wyraź swoje prawdziwe uczucia do niego.',
    'Taniec breakdance do miłosnej piosenki z kimś z tego pokoju.',
    'Zadzwoń do rodziców i powiedz im, że spodziewasz się dziecka.',
    'Napisz szczegółowy status swojej ostatniej randki ze swoim partnerem.',
    'Ćwicz taniec na rurze i wyślij film swojemu partnerowi',
    'Podziel się sekretem swojego ostatniego byłego.',
    'Nagraj film, w którym tańczysz pod prysznicem w ubraniu.',
    'Spróbuj polizać łokieć.',
    'Daj każdemu zgadnąć, kto jest Twoim ulubionym członkiem tej grupy.',
    'Opowiedz nam o rzeczach, których najbardziej nie lubisz w swoim życiu.',
    'Wykonuj balet bez muzyki.',
    'Użyj ust, aby nakarmić kogoś owocem.',
    'Połóż się na podłodze i pozwól komuś narysować zarys twojego ciała.',
    'Zrób komuś w tym pokoju masaż całego ciała.',
    'Wyślij SMS-a do swojej sympatii, a następnie przeproś, mówiąc, że to pomyłka.',
    'Wyślij wiadomość głosową do swojej sympatii.',
    'Wyłącz światło i przytul pierwszą osobę, której możesz dotknąć.',
    'Odegraj małą część sztuki „Romeo i Julia”.',
    'Spróbuj rozśmieszyć osobę naprzeciwko.',
    'Ustaw dziwne zdjęcie siebie jako tapetę telefonu.',
    'Znajdź swoje zdjęcie z dzieciństwa i spróbuj odtworzyć je jak najdokładniej.',
    'Zatańcz improwizowany taniec przez minutę.',
    'Zaśpiewaj piosenkę karaoke.',
    'Zadzwoń do losowej osoby i powiedz, że ją kochasz.',
    'Poproś przechodnia o autograf.',
    'Zaśpiewaj piosenkę z zamkniętymi ustami.',
    'Wykrzycz pierwsze słowo, które w tej chwili przychodzi ci na myśl.',
    'Naśladuj swojego ulubionego celebrytę',
    'Zamknij oczy i spróbuj wysłać wiadomość w ciemno do dowolnej osoby',
    'Weź miotłę i zatańcz z nią tango',
    'Wymyśl historię o osobie po twojej prawej',
    'Powiedz pierwsze słowo, które przyszło ci na myśl',
    'Używaj tylko języka migowego do następnej rundy',
    'Idź do domu sąsiada i poproś o banana',
    'Zrób wiersz dla swojego partnera',
    'Naśladuj staruszkę lub staruszka',
    'Obróć się 10 razy i spróbuj iść w linii prostej',
    'Wykonaj 10 pompek',
    'Wstrzymaj oddech na 30 sekund',
    'Napisz do nauczyciela, jak minął ci dzień',
    'Zaprezentuj improwizowany skecz na zadany temat.',
    'Udawaj, że jesteś na wybiegu modelek przez 10 sekund.',
    'Zrób minę, jakbyś właśnie zjadł coś bardzo gorzkiego.',
    'Przejdź przez cały pokój chodząc po piętach.',
    'Zadzwoń do swojego byłego i powiedz mu/jej, że myślałeś/aś o nim/niej.',
    'Zaproś na swojego Instagrama osobę, którą spotkałeś/aś tylko raz w życiu.',
    'Opowiedz dowcip tak śmieszny, że wszyscy będą śmiać się na głos.',
    'Powiedz komuś, kogo nie znasz, że jesteś z nim spokrewniony/a i wymyśl nazwisko.',
    'Przez następne 5 minut mów tylko wierszem.',
    'Nakarm drugą osobę czymś z zamkniętymi oczami.',
    'Zatańcz jakbyś miał/miała owady w majtkach!',
    'Pokaz Twoje ostatnie zdjęcie w galerii',
    'Naśladuj kogoś w grupie.',
    'Odegraj scenę z ulubionego filmu, aż ktoś zgadnie co to za film.',
    'Udawaj innego gracza i poproś grupę, żeby zgadła, kogo udajesz.',
    'Zamień się jednym elementem ubrania z osobą po twojej prawej.',
    'Przenieś na rękach jednego z graczy po całym pokoju.',
    'Zacznij lizać swój nos.',
    'Przeczytaj na głos ostatnią wiadomość, jaką dostałeś(-łaś).',
    'Udawaj zwierzę wybrane przez grupę.',
    'Zadzwoń do nieznajomej osoby i upieraj się, że to ona pierwsza do ciebie zadzwoniła.',
    'Wskaż osobę, która najłatwiej da się nabrać na internetowe oszustwo.',
    'Poliż klamkę.',
    'Zatańcz z osobą po twojej prawej do piosenki wybranej przez innych.',
    'Otwórz okno i głośno zaśpiewaj hymn narodowy!',
    'Narysuj bałwana.',
    'Nie możesz rozmawiać przez 2 tury.',
    'Naśladuj kota.',
    'Wyzywam cię do wstania na 2 tury.',
    'Nazwij wszystkie oceany.',
    'Zatańczmy Macarena wszyscy razem.',
    'Zaśpiewaj swoją ulubioną piosenkę.',
    'Stwórz wiersz używając słów pomarańczowy i łoś.',
    'Stań na jednej nodze przez następne dwie rundy.',
    'Masz szczęście, zyskałeś minutowy masaż od gracza po prawej stronie.',
    'Połóż nogę za głową.',
    'Bądź ludzkim kocem (rozgrzej kogoś).',
    'Wskaż kogoś, kto musi coś zaśpiewać.',
    'Opowiedz nam o swoim ostatnim śnie.',
    'Wymień 7 cudów lub 7 grzechów głównych.',
    'Wszyscy zamieniają się miejscami.',
    'Naśladuj starego, zrzędliwego mężczyznę, który narzeka na dawne czasy.',
    'Taniec brzucha do piosenki country.',
    'Znajdź 3 wypchane zwierzęta i udaj się na herbatę lub przyjęcie urodzinowe.',
    'Wykonaj nakrycie głowy z papieru toaletowego i pozuj do zdjęć.',
    'Wydawaj dźwięki pierdzenia przez 30 sekund.',
    'Zrób 20 przysiadów.',
    'Stwórz freestyle rapową piosenkę o każdej osobie w grupie.',
    'Biegaj po pokoju naśladując małpę.',
    'Weź kogoś na kolana na 2 rundy.',
    'Śpiewaj zamiast mówić przez następne dwie rundy gry.',
    'Nie możesz mówić przez 2 rundy.',
    'Recytuj tabliczkę mnożenia z 6.',
    'Wykonaj 10 skoków.',
    'Zrób papierowy płatek śniegu.',
    'Przytul osobę siedzącą najbliżej Ciebie',
    'Weź na barana osobę po prawej stronie',
    'Zapiej jak kogut',
    'Opowiedz suchara',
    'Wyrwij sobie jeden włos z głowy',
    'Zatańcz „kaczuszki”',
    'Przez 30 sekund udawaj, że grasz na gitarze',
    'Udawaj, że boli Cię gardło',
    'Uszczypnij pośladki osoby po Twojej lewej stronie',
    'Klęcz przez minutę',
    'Udawaj, że z przejęciem czytasz gazetę',
    'Postaraj się nie mrugać przez 30 sekund. Jeżeli mrugniesz to reszta grupy wymyśla karę',
    'Powiedz szczerze osobie po Twojej lewej coś niewygodnego',
    'Udawaj konia przez minutę',
    'Niech każdy gracz oceni cię w skali od 1-10',
    'Złap się za biodra i pokręć nimi',
    'Zamknij oczy. Reszta graczy piszę / rysuje dowolną rzecz na Twoim czole. Do końca gry nie możesz tego zobaczyć.',
    'Zrób zeza',
    'Zatańcz z miotłą lub mopem',
    'Udawaj dramatycznie scenę śmierci',
    'Udawaj drzewo przez minutę',
    'Wejdź pod krzesło',
    'Zrób 3 minutowy stand up',
    'Przez minutę przedstawiaj główne wydanie wiadomości',
    'Przez 2 kolejne rundy posługuj się językiem obcym. Reszta grupy wybiera jakim.',
    'Opowiedz coś śmiesznego',
    'Spraw aby każda osoba w grupie się uśmiechnęła',
    'Złap się za tyłek i pokreć nim',
    'Zamknij lewe oko na minutę',
    'Zatańcz jak robot',
    'Stój na palach przez minutę',
    'Powiedz kawał',
    'Przybij piątkę z każdym w tym pomieszczeniu',
    'Dobierz się z kimś w parę. Spodziewacie się dziecka. Zagrajcie scenkę narodzin dziecka',
    'Podejdź do jakiejś osoby z tego pokoju(wybiera reszta grupy) i powiedz, że chciałbyś/aś się z nim przespać',
    'Udawaj komara',
    'Reszta graczy układa Ci fryzurę. Musisz w niej pozostać do końca gry.',
    'Chodź na czworaka przez minutę',
    'Siedź jak budda przez 3 minuty',
    'Weź długopis w usta i napisz coś na kartce',
    'Na czworaka zachowuj się jak świnia przez 10 sekund'
]
let losowe = Math.floor(Math.random() * 10)
// console.log(losowe)

function losujLiczbyBezPowtorzen(ilosc, zakres) {
    var liczbyP = [];
    var liczbyW = [];
    for (var i = 1; i <= zakresLiczbPrawda; i++) {
      liczbyP.push(i);
    } 
    for (var i = 1; i <= zakresLiczbWyz; i++) {
        liczbyW.push(i);
      } 
    var wynikP = [];
    var wynikW = [];
    for (var j = 0; j < iloscLiczbPrawda; j++) {
      var losowyIndexP = Math.floor(Math.random() * liczbyP.length);
      var wylosowanaLiczbaP = liczbyP.splice(losowyIndexP, 1)[0];
      wynikP.push(wylosowanaLiczbaP);
    //   console.log(pyt[wynik[j]])
    }
    for (var k = 0; k < iloscLiczbWyz; k++) {
        var losowyIndexW = Math.floor(Math.random() * liczbyW.length);
        var wylosowanaLiczbaW = liczbyW.splice(losowyIndexW, 1)[0];
        wynikW.push(wylosowanaLiczbaW);
      //   console.log(pyt[wynik[j]])
      }
      
    PRAWDA.addEventListener('click', function() {
        if(iloscPrawd >=pyt.length) {
            alert('Pula pytań wyczerpana')
        } else {
            PRAWDA.classList.toggle('ukryty')
            WYZWANIE.classList.toggle('ukryty')
            RESET.classList.toggle('ukryty')
                TEKST.innerHTML = `
                    <p id='head1' class='header'>${pyt[wynikP[iloscPrawd]]}</p>
                    <p id='head2' class='header'>${pyt[wynikP[iloscPrawd]]}</p>
                    <p id='head3' class='header'>${pyt[wynikP[iloscPrawd]]}</p>
                    <p id='head4' class='header'>${pyt[wynikP[iloscPrawd]]}</p>
                    <p id='head5' class='header'>${pyt[wynikP[iloscPrawd]]}</p>
                `
                iloscPrawd++
        }
    })

    RESET.addEventListener('click', function() {
        PRAWDA.classList.toggle('ukryty')
        WYZWANIE.classList.toggle('ukryty')
        RESET.classList.toggle('ukryty')

        TEKST.innerHTML = ''
    })
    //383 pytan 
    //167 wyzwan
    
    WYZWANIE.addEventListener('click', function() {
        if(iloscWyzwan>=wyz.length) {
            alert('Pula pytań wyczerpana')
    } else {
            PRAWDA.classList.toggle('ukryty')
            WYZWANIE.classList.toggle('ukryty')
            RESET.classList.toggle('ukryty')

            {
                TEKST.innerHTML = `
                    <p id='head1' class='header'>${wyz[wynikW[iloscWyzwan]]}</p>
                    <p id='head2' class='header'>${wyz[wynikW[iloscWyzwan]]}</p>
                    <p id='head3' class='header'>${wyz[wynikW[iloscWyzwan]]}</p>
                    <p id='head4' class='header'>${wyz[wynikW[iloscWyzwan]]}</p>
                    <p id='head5' class='header'>${wyz[wynikW[iloscWyzwan]]}</p>
                `
                // console.log(wyz[wynikW[iloscWyzwan]])

                iloscWyzwan++
        }
    }})
    return wynikP,wynikW;
  }
  
  var iloscLiczbPrawda = pyt.length - 1;
  var zakresLiczbPrawda = pyt.length - 1;
  var iloscLiczbWyz = wyz.length - 1;
  var zakresLiczbWyz = wyz.length - 1;
  var wylosowaneLiczby = losujLiczbyBezPowtorzen(iloscLiczbPrawda, zakresLiczbPrawda);
//   var wylosowaneLiczby2 = losujLiczbyBezPowtorzen(iloscLiczbWyz, zakresLiczbWyz); //






